[package]
name = "lodtree"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev_dependencies]
rayon = "1.5"
glium = "0.30"
